project:
  type: website
  output-dir: docs
  
website:
  title: "Astrid Van Haren Web Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: github
        href: https://github.com/avh405/Assignment5
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Astrid Van Haren"

format:
  html:
    theme: cerulean
    toc: true

editor: source
